version: "3.9"
services:
  elasticsearch:
    image: elasticsearch:8.5.2
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - xpack.security.enabled=false
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - target: 9200
        published: 9200

  kibana:
    image: kibana:8.5.2
    ports:
      - target: 5601
        published: 5601
    depends_on:
      - elasticsearch   

volumes:
  es-data:
