version: "3.9"
services:
  elasticsearch:
    image: elasticsearch:8.5.2
    environment:
      - discovery.type=single-node
      # edit memory usage, currently 128Mb (use 1g to set it to 1Gb)
      - ES_JAVA_OPTS=-Xms128m -Xmx128m
      - xpack.security.enabled=false
    volumes:
      - es-data:/usr/share/elasticsearch/data
    ports:
      - target: 9200
        published: 9200

  # Uncomment to use Kibana alognside Elastic
  # kibana:
  #   image: kibana:8.5.2
  #   ports:
  #     - target: 5601
  #       published: 5601
  #   depends_on:
  #     - elasticsearch

  mongo:
    image: mongo
    volumes:
      - mongo-data:/data/db
    ports:
      - 27017:27017

volumes:
  es-data:
  mongo-data:
